spring.application.name=hufds

spring.datasource.url=jdbc:postgresql://localhost:5432/hufdsdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.user.name=user
spring.security.user.password=1234
logging.level.org.springframework.security=DEBUG

google.api.key=AIzaSyBkEQfPxLwjzhWwPshlQAdIuWTHlk80Vls
secret.key=f93$Lk20mXs82Pa0@jdP!v0v_34MxL2vAZe5t8aB
expiration.time=86400000

server.port=8080