spring.application.name=hufds

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
 spring.datasource.username=${PGUSER}
 spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.user.name=user
spring.security.user.password=1234
logging.level.org.springframework.security=DEBUG

google.api.key=AIzaSyBkEQfPxLwjzhWwPshlQAdIuWTHlk80Vls
secret.key=f93$Lk20mXs82Pa0@jdP!v0v_34MxL2vAZe5t8aB
expiration.time=86400000

spring.main.allow-bean-definition-overriding=true

restaurant.image.upload-dir=src/main/resources/static/images/restaurants

server.port=8080

app.frontend.reset-password-url=https://purpleworld.tr/reset-password

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.purpleworld@gmail.com
spring.mail.password=oqeg qadb mooh tkxd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
